version: '3'
services:
  strapi:
    image: ghcr.io/harrytang/headless.harrytang.xyz:main
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mariadb
      DATABASE_PORT: 3306
      DATABASE_NAME: ${MYSQL_DATABASE}
      DATABASE_USER: ${MYSQL_USER}
      DATABASE_PASS: ${MYSQL_PASSWORD}
      DATABASE_SSL: 'false'
      URL: https://headless-local.harrytang.xyz
    volumes:
      - ./app:/srv/app
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.5
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  proxy:
    image: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./proxy/upstream.conf:/etc/nginx/conf.d/upstream.conf
      - ./proxy/strapi.conf:/etc/nginx/conf.d/strapi.conf
      - ~/certs/harrytang.xyz/fullchain.pem:/etc/nginx/certs/fullchain.pem
      - ~/certs/harrytang.xyz/key.pem:/etc/nginx/certs/key.pem
    depends_on:
      - strapi
